        params.relearn.RHS.modify     = 1;
        relearn_parameter      = struct(                            ...
                    'N_relearn',          2*params.RHS.N,                       ...
                    'iter',               1,                         ...
                    'RHS_parameter',      params.relearn.RHS,     ...
                    'relative_threshold',  [0.005, 0.02],            ...
                    'simulator_par',      @(Sim_parameter) simEulernonlintrans_par(params.relearn.RHS,Sim_parameter) ...
                    );


        disp('Starting Relearning Chart')
        K                                     = length(chart);
        index_to_learn                        = 1:K;
        [ chart,~ ]                           = relearn_chart(chart, relearn_parameter, index_to_learn);
        [chart, connectivity, P]              = landmark(chart, params.RHS.t0, params.RHS.chi_p,params.RHS.threshold(1), params.RHS.connectivity_threshold);
        save( params.paths.chart ,'chart','connectivity','P')

        disp('Relearning stage is completed.')
