
    Sim_parameter                      = struct(        ...
                             'T_max',        params.learning.T_one*3,   ...
                             'dt',           params.RHS.dt ,       ...
                             'gap',          1,         ...
                             'X_int',        params.learning.X_int      ...
        );

    [output]                          = params.simulator.one(Sim_parameter);
    [L_out,~]                         = size(output);
    temp                              = params.RHS.nonlin_trans_inv(output');
    phi_ori                           = temp(1,:);
     disp(['one single traj is simulated with the original simulator'])
