function params = set_parameter()
%SET_PARAMETER Configure simulation, learning, and analysis settings for Butane.
%
%   params = SET_PARAMETER() returns a struct with the configuration that was
%   previously populated in the base workspace. The struct is organised into
%   topical fields (RHS, simulator, learning, chart_sim_parameter, relearn,
%   paths, etc.) so downstream workflows can reference the data explicitly.

  datapath = evalin('base','datapath');

  D         = 6;                   % The dimension of the full system
  d         = 1;                   % The dimension of the slow manifold. Later we can estimate this dimension
  chi_p     = 1.96;                % for 95% Confidence interval for 1D Gaussian distribution
  K_int     = 2;                   % Number of initial points on the manifold.
  N         = 1600000;             % Number of short trajectories starting from the same initial point
  dt        = 1*10^-6;             % Simulation time-step
  T_one     = 10;                  % Time for single long trajectory to learn initial K charts.
  relearn_option     = 1;          % option to relearn

  t0                     = 10*dt;  % The time as the benchmark. Drift and diffusion varies small within t0
  T_max                  = 50*dt;  % Time for short trajectories.
  X_int                  = [  -1.4461    0.5578   1.5361    1.4268   -2.0593    0.1615] + 0.1*randn(1,6);
  threshold              = [1.5, 0.001];  % First value R_max, second threshold for occasional projection
  connectivity_threshold = 4;      % Two landmarks are connected if within r*sqrt(t0)
  explore_threshold      = 0.95;
  option                 = 1;      % 1 for fast mode projection, 2 for orthogonal projection
  modify                 = 0;      % 0 use the intercept(t=0) 1 use the tau_min point as the landmark
  % The training window is larger than the relaxation here. It is to ensure
  % the landmark is sufficiently relaxed onto the manifold
  LowerBound             = 40*dt;   % Lower bound of the training window
  UpperBound             = 50*dt;   % Upper bound of the training window

  % Parameters for simulation
  Nstep                  = 2*10^2;
  gap                    = 10;

  % Parameters for RHS
  l                      = 1.53;
  k2                     = 319225; % 1.17*10^6;
  k3                     = 62500;
  theta                  = 112/180*pi; % 112 degree
  c1                     = 2037.82;
  c2                     = 158.52;
  c3                     = -3227.70;
  beta                   = 4*10^-3;
  sigma                  = sqrt(2*beta^(-1));

  parameter              = struct(       ...
      'l',             l,                ...
      'k2',            k2,               ...
      'k3',            k3,               ...
      'theta',         theta,            ...
      'c1',            c1,               ...
      'c2',            c2 ,              ...
      'c3',            c3 ,              ...
      'sigma',         sigma             ...
     );

  drift                    = @(X) get_drift(X, parameter);
  diffusion                = @(X) get_diffusion(X, parameter);
  RHS_parameter = struct(                  ...
    'dt',             dt ,               ...
    'T_max',          T_max ,            ...
    'N',              N,                 ...
    't0',             t0,                ...
    'chi_p',          chi_p,             ...
    'threshold',      threshold,         ...
    'modify',         modify,            ...
    'connectivity_threshold',connectivity_threshold, ...
    'D',              D,                 ...
    'd',              d,                 ...
    'parameter',      parameter,         ...
    'drift',          drift,             ...
    'diffusion',      diffusion,         ...
    'UpperBound',     UpperBound,        ...
    'LowerBound',     LowerBound         ...
);

% Setup simulator
  simulator_one                 = @(Sim_parameter) simEuler_one_traj(RHS_parameter,Sim_parameter);
  simulator_no_par              = @(Sim_parameter) simEuler(RHS_parameter,Sim_parameter);
  simulator_par                 = @(Sim_parameter) simEuler_par(RHS_parameter,Sim_parameter);

  MSM_parameter        = struct(           ...
            'step',               1,      ...
            'N_state',            1*10^6, ...
            'dt_s',               10*dt      ...
            );

  chart_sim_parameter      = struct (                                                   ...
                                      'X_int',                   [],                  ...
                                      'nearest',                 1,                   ...
                                      't0',                      t0,                  ...
                                      'dt_s',                    10*dt,               ...
                                      'D',                       RHS_parameter.D,     ...
                                      'd',                       RHS_parameter.d,     ...
                                      'Nstep',                   Nstep,               ...
                                      'gap',                     gap,                 ...
                                      'connectivity',            [],                  ...
                                      'explore_threshold',       explore_threshold,   ...
                                      'N',                       N                    ...
                                     );

 % Parameters for relearn chart

  RHS_parameter_relearn  = RHS_parameter; % one can change some RHS if you believe the invariant manifold is not changed.
  relearn_parameter      = struct(                            ...
            'N_relearn',          6*N,                       ...
            'iter',               15,                        ...
            'RHS_parameter',      RHS_parameter_relearn,     ...
            'relative_threshold',  [0.01, 0.05],            ...
            'simulator_par',      @(Sim_parameter) simEuler_par(RHS_parameter_relearn,Sim_parameter) ...
            );

 % Parameters for MFPT length
  N_IC                  = 30000;

 % File paths
  chart_fileName                = [datapath,'chart.mat'];
  chart_part_fileName           = [datapath,'chart_part.mat'];
  chart_plot_fileName           = [datapath,'chart_plot.mat'];
  TranM_fileName                = [datapath,'TranM.mat'];
  TranM_plot_fileName           = [datapath,'TranM_plot.mat'];
  chart_relearn_fileName        = [datapath,'chart_relearn.mat'];
  well_fileName                 = [datapath,'well.mat'];
  FPT_fileName                  = [datapath,'Butane_FPT.mat'];

  params = struct();
  params.RHS = RHS_parameter;
  params.simulator = struct( ...
      'one', simulator_one, ...
      'serial', simulator_no_par, ...
      'parallel', simulator_par ...
  );
  params.MSM = MSM_parameter;
  params.chart_sim_parameter = chart_sim_parameter;
  params.relearn = struct( ...
      'option', relearn_option, ...
      'RHS', RHS_parameter_relearn, ...
      'settings', relearn_parameter ...
  );
  params.learning = struct( ...
      'K_int', K_int, ...
      'T_one', T_one, ...
      'X_int', X_int, ...
      'explore_threshold', explore_threshold, ...
      'option', option ...
  );
  params.simulation = struct( ...
      'Nstep', Nstep, ...
      'gap', gap ...
  );
  params.paths = struct( ...
      'datapath', datapath, ...
      'chart', chart_fileName, ...
      'chart_part', chart_part_fileName, ...
      'chart_plot', chart_plot_fileName, ...
      'TranM', TranM_fileName, ...
      'TranM_plot', TranM_plot_fileName, ...
      'chart_relearn', chart_relearn_fileName, ...
      'well', well_fileName, ...
      'FPT', FPT_fileName ...
  );
  params.MFPT = struct('N_IC', N_IC);
end
